apiVersion: v1
kind: Service
metadata:
  name: mongodbservice
  labels:
    name: mongodbservice
    app: mongodb
spec:
  type: LoadBalancer
  selector:
    app: mongodb
  ports:
    - port: 27017
      targetPort: 27017
      protocol: TCP